export const PackagesData = [

    {
      id: 1,
      smallImg: '/img31.webp',
      largeImg:'/large31.jpg',
      location: 'Paris, France',
      stars: 4.5,
      description: 'Experience the romantic city of lights.',
      rate: '$1200',
      detailDesc:"Paris lives up to its hype: A city with unbelievable food and culture, plus stunning views everywhere you turn. With 18 arrondissements, it’s a lot to see in one trip, but each neighbourhood has a personality all its own. You can’t miss the iconic 7th, where art and history meet—there’s the Eiffel Tower, sure, but the impressive Musée du quai Branly is just a short walk away. It houses an amazing collection of indigenous art. Or, hit up Montmartre (the 18th), with its boho shops and cosy brasseries. It’s a must-stop on the way up or down from Sacre Coeur. While the French practically invented fine dining, don’t skip the street food—Paris has world-class kebabs and falafel. But no matter where you are, be sure to pop into a sidewalk cafe, sip a glass of wine, and people watch—it’s the way to get a taste of true Parisian culture.",
      thing:'the Eiffel Tower, wander around the Louvre, take a day trip to Versailles, or try a sightseeing tour to uncover even more art, history, and undeniable charm..',
      hotelurl:"https://www.tripadvisor.in/Hotel_Review-g187147-d228694-Reviews-Hotel_Malte_Astotel-Paris_Ile_de_France.html",
      resturanturl:"https://www.tripadvisor.in/Restaurants-g187147-Paris_Ile_de_France.html",
      flighturl:"https://www.tripadvisor.in/Flights-g187147-Paris_Ile_de_France-Cheap_Discount_Airfares.html",
    },

    {
      id: 2,
      smallImg: '/img32.webp',
      largeImg: '/large32.jpg',
      location: 'kyoto, Japan',
      stars: 4.7,
      description: 'Explore the beautiful temples and gardens.',
      rate: '$1500',
      detailDesc:'Kyoto, Japan’s capital for over 1,000 years, offers a rare link between modern life in a city and its very ancient past. Here, Buddhist temples, Shinto shrines, Zen rock gardens, and UNESCO World Heritage Sites are at every turn. Visit the 7th-century Shimogamo Shrine with its stunning arcade of orange gates, the elegant Kinkakuji Temple with a gold-leaf exterior perfectly reflected in a placid lake, and Kiyomizu-dera Temple with a hillside location that makes for spectacular city views. Still the centre of traditional Japanese culture, Kyoto is the place to experience a tea ceremony, savour multi-course Kaiseki haute cuisine, and catch sight of a geisha as you stroll through Gion at dusk. For the very best of Kyoto.',
      thing:'Fushimi Inari-taisha Shrine, Kinkakuji Temple, Sacred & Religious Sites, Historic Sites. For personalised recommendations',
      hotelurl:'https://www.tripadvisor.in/Hotels-g298564-Kyoto_Kyoto_Prefecture_Kinki-Hotels.html',
      resturanturl:'https://www.tripadvisor.in/Restaurants-g298564-Kyoto_Kyoto_Prefecture_Kinki.html',
      flighturl:'https://www.tripadvisor.in/Flights-g298564-Kyoto_Kyoto_Prefecture_Kinki-Cheap_Discount_Airfares.html',
    },

    {
      id: 3,
      smallImg: '/img33.webp',
      largeImg:'/large33.jpg',
      location: 'New York, USA',
      stars: 4.3,
      description: 'Enjoy the bustling streets and skyline.',
      rate: '$1000',
      detailDesc: 'The tallest skyscrapers, the biggest museums, the cheesiest pizza. New York City takes everything to the max. It’s easy to see why it’s the most-visited place in the U.S.: Whether you want to check out historic landmarks, catch a Broadway show, or stroll the streets of Brooklyn, there’s no wrong way to do it—and something new to discover every time you go. Spend the day neighbourhood-hopping, from the family-friendly Upper West Side packed with playgrounds and cute restaurants to the gritty-but-cool Lower East Side, each has its own vibe. Browse art galleries in Chelsea, go shopping in SoHo, then grab a drink in the East Village. Or, take the subway (or walk across the Brooklyn Bridge) and cruise the cobblestone streets in Dumbo. Want some nature? It’s got that, too. Have a picnic in Central Park, hit the High Line, or hop on a ferry and see the city from the sea.',
      thing:'Start with sightseeing NYC’s greatest hits: Times Square, the Empire State Building, the Statue of Liberty, and spend the rest of your time checking out neighbourhood gems.',
      hotelurl:'https://www.tripadvisor.in/Hotels-g60763-New_York_City_New_York-Hotels.html',
        resturanturl:'https://www.tripadvisor.in/Restaurants-g60763-New_York_City_New_York.html',
        flighturl:'https://www.tripadvisor.in/Flights-g60763-New_York_City_New_York-Cheap_Discount_Airfares.html',
    },

    {
      id: 4,
      smallImg: '/img34.webp',
      largeImg:'/large34.jpg',
      location: 'Goa, India',
      stars: 4.6,
      description: 'Enjoy scenic beaches and vibrant nightlife.',
      rate: '$850',
      detailDesc:'East meets West in this sun-soaked state, where Indian culture intertwines with Portuguese influences left over from a 500-year occupation. The beaches have long served as a magnet for serene hedonists. To the north, the tourist-centric scene is prevalent, with an international flair that is now skewing more hip than hippie. Travel south for stretches of unspoiled sand and an escape from large resorts. Temples, mosques and wildlife sanctuaries provide diversions from the beach.',
       thing:'Check out must-see sights and activities:Palolem Beach, Baga Beach, Beaches, Sacred & Religious Sites.',
       hotelurl:'https://www.tripadvisor.in/Hotels-g297604-Goa-Hotels.html',
       resturanturl:'https://www.tripadvisor.in/Restaurants-g297604-Goa.html',
       flighturl:'https://www.tripadvisor.in/Flights-g297604-Goa-Cheap_Discount_Airfares.html',
    },
    {
      id: 5,
      smallImg: 'img35.webp',
      largeImg:'/large35.jpg',
      location: 'Sydney, Australia',
      stars: 4.8,
      description: 'Visit the iconic Opera House and beaches.',
      rate: '$1400',
      detailDesc:'Sydney is a place that’s really got it all: It’s a sunny, modern city, right smack in the middle of nature, where gallery-hopping, surfing, and fine dining can all happen before the sun goes down. Start with the views: Take the cliff top coastal walk from Bondi to Coogee, where you’ll pass by beaches, rock pools, and lush parks. Then there’s the world-famous Sydney Opera House—jutting up like a huge sailboat—anchoring iconic Sydney Harbour. It’s also worth seeing the city from the top down; the views from the Sydney Tower Eye observatory are nothing less than epic.',
      thing:'Check out must-see sights and activities:Sydney Opera House, Manly Beach, Points of Interest & Landmarks, Art Galleries',
      hotelurl:'https://www.tripadvisor.in/Hotels-g255060-Sydney_New_South_Wales-Hotels.html',
      resturanturl:'https://www.tripadvisor.in/Restaurants-g255060-Sydney_New_South_Wales.html',
      flighturl:'https://www.tripadvisor.in/Flights-g255060-Sydney_New_South_Wales-Cheap_Discount_Airfares.html',
    },
    {
      id: 6,
      smallImg: 'img36.webp',
      largeImg:'/large36.jpg',
      location: 'Rome, Italy',
      stars: 4.4,
      description: 'Explore ancient ruins and vibrant culture.',
      rate: '$1100',
      detailDesc:'It’s easy to see why Rome’s one of the most-visited places on the planet: There’s history everywhere (the Pantheon, the Colosseum, the list goes on), sculptural masterpieces in almost every piazza, and—of course—ridiculously good food. Every trip could feel like a whirlwind, but slow down and you’ll discover lots of surprises. Spend a Sunday morning in Trastevere and hunt for vintage finds at Porta Portese flea market. Or hit San Lorenzo—a student neighbourhood with an edgy-but-charming vibe—for trendy shops, galleries, and street art. Dinner’s not ‘til late here, so grab an aperitivo in Prati—it’s walkable from the Vatican and packed with quirky sidestreet bars.Yes, the energy’s next-level, so if you need a break, head for the hills (literally) and check out Aventine Hill, a leafy-green suburb with peaceful gardens and some of the best views of the city',
      thing:'In between bites of pasta and pizza, discover ancient architecture like the Colosseum, Pantheon, and Trevi Fountain—get a local guide to show you all the hidden gems.',
       hotelurl:'https://www.tripadvisor.in/Hotels-g187791-Rome_Lazio-Hotels.html',
      resturanturl:'https://www.tripadvisor.in/Restaurants-g187791-Rome_Lazio.html',
      flighturl:'https://www.tripadvisor.in/Flights-g187791-Rome_Lazio-Cheap_Discount_Airfares.html',
    },
    {
      id: 7,
      smallImg: 'img37.webp',
      largeImg:'/large37.jpg',
      location: 'Bali, Indonesia',
      stars: 4.7,
      description: 'Relax on beautiful beaches and resorts.',
      rate: '$900',
      detailDesc:'Bali packs a lot into one small island— from breathtaking waterfalls like Sekumpul in the north to the white sand beaches of Nyang Nyang in the south. Whatever you’re seeking, you’ll probably find: surf-able waves in Batu Bolong, all-night clubs in Seminyak, luxury clifftop hotels in Nusa Dua, and spiritual refuges all around. Snap a pic at the Gateway to Heaven, cut through the jungle to the hidden Gunung Kawi Temple, and catch the sunset and a traditional fire dance at Uluwatu Temple. Just don’t miss the markets—hunt for handcrafted artwork and textiles at the Sukawati Art Market, or snack on street food staples like satay and bakso at the Sindhu Night Market.',
      thing:'Check out must-see sights and activities:Waterbom Bali, Sacred Monkey Forest Sanctuary, Sacred & Religious Sites, Beaches. ',
      hotelurl:'https://www.tripadvisor.in/Hotels-g294226-Bali-Hotels.html',
      resturanturl:'https://www.tripadvisor.in/Restaurants-g294226-Bali.html',
      flighturl:'https://www.tripadvisor.in/Flights-g294226-Bali-Cheap_Discount_Airfares.html',
      
    },
    {
      id: 8,
      smallImg: 'img38.webp',
      largeImg:'/large.jpg',
      location: 'Barcelona, Spain',
      stars: 4.5,
      description: 'Enjoy stunning architecture and nightlife.',
      rate: '$1250',
      detailDesc:'When it comes to history, art, and architecture, Barcelona delivers. There’s Gaudí’s iconic Basílica de la Sagrada Familia, the Picasso Museum, and the Gothic Quarter. But look beyond the landmarks and busy mercados and you’ll notice how nature steals the show—the city’s literally surrounded by it. On one side you’ve got three miles of gorgeous sandy beaches that give the neighbouring Balearic Islands a run for their money, and on the other, the Serra de Collserola mountains, home to Parc de Collserola—one of the biggest city parks in the world. It’s probably why bike culture’s big here: Over 180 miles of bike lanes make it easy to get around the Catalan capital. Spend a low-key afternoon cruising the revamped La Rambla (you’ll have to walk your bike once you hit the pedestrian-only drag) and stop for tapas and sangria.',
      thing:'Plan ahead and book tours of the Sagrada Familia and Picasso Museum, then shop, sip, or savour your way through Las Ramblas and the Gothic Quarter.',
      hotelurl:'https://www.tripadvisor.in/Hotels-g187497-Barcelona_Catalonia-Hotels.html',
      resturanturl:'https://www.tripadvisor.in/Restaurants-g187497-Barcelona_Catalonia.html',
      flighturl:'https://www.tripadvisor.in/Flights-g187497-Barcelona_Catalonia-Cheap_Discount_Airfares.html',
    },
    {
      id: 9,
      smallImg: 'img39.webp',
      largeImg:'/large39.jpg',
      location: 'Dubai, UAE',
      stars: 4.6,
      description: 'Experience luxury shopping and desert safaris.',
      rate: '$1600',
      detailDesc:'Everything feels extra spectacular in Dubai—from the ultra-modern Burj Khalifa to the souks and malls filled with gold and jewellery vendors. It’s a place where if you can dream it, you can do it: Whether that means skiing indoors, dune-surfing in the desert, or zip-lining above the city. But it’s not all glitz and adrenaline-pumping action. Stroll through the winding alleys of Al Fahidi Historical Neighbourhood to see what Dubai was like during the mid-19th century. Or visit the Jumeirah Mosque (one of the few mosques open to non-Muslims) and learn about Emirati culture. Spot some street art on Jumeirah Beach Road and grab a bite at a shawarma shop, or spend the day hunting for spices and perfume then round things out with a Michelin-starred meal.',
      thing:'Take in cutting-edge architecture like the Burj Khalifa and Dubai Fountain with a city tour or try some more adventure activities and explore the desert by camel or ATV.',
      hotelurl:'https://www.tripadvisor.in/Hotels-g295424-Dubai_Emirate_of_Dubai-Hotels.html',
      resturanturl:'https://www.tripadvisor.in/Restaurants-g295424-Dubai_Emirate_of_Dubai.html',
      flighturl:'https://www.tripadvisor.in/Flights-g295424-Dubai_Emirate_of_Dubai-Cheap_Discount_Airfares.html',
    },
    {
      id: 10,
      smallImg: 'img40.webp',
      largeImg:'/large40.jpg',
      location: 'Phuket, Thailand',
      stars: 4.3,
      description: 'Enjoy vibrant nightlife and scenic beaches.',
      rate: '$850',
      detailDesc:'You can really do it all in Phuket: Party ‘til dawn, kick back on a sandy shore, discover hidden temples, stroll through local markets. Yes, the beaches are next level (and definitely worth a stop), but head further inland to the old quarter for a peek into Phuket’s past, and eateries serving up chili and blue ginger-spiced dishes. Whether you want to relax or take things up a notch there’s no wrong way to do it.',
      thing:'Check out must-see sights and activities:Bangla Road, Big Buddha Phuket, Sports Camps & Clinics, Beaches.',
      hotelurl:'https://www.tripadvisor.in/Hotels-g293920-Phuket-Hotels.html',
      resturanturl:'https://www.tripadvisor.in/Restaurants-g293920-Phuket.html',
      flighturl:'https://www.tripadvisor.in/Flights-g293920-Phuket-Cheap_Discount_Airfares.html',
    },
    {
      id: 11,
      smallImg: 'img41.webp',
      largeImg:'/large41.jpg',
      location: 'Reykjavik, Iceland',
      stars: 4.8,
      description: 'Witness stunning natural landscapes and geysers.',
      rate: '$1800',
      detailDesc:'For most visitors, Reykjavik is a gateway to the out-of-this-world natural sites that make up the Golden Circle, like Geysir Geothermal Area, Gullfoss Waterfall and Thingvellir National Park. But the city itself deserves a few itinerary days to help you get a feel for Icelandic culture. Start by digging into Nordic food (order anything with fish or lamb), then dive into Reykjavik’s legendary music scene—it’s a hub for the indie and electronic musicians that fuel its nightlife. Afterwards, recharge in one of the area’s many hot springs. You can’t go wrong with a soak in the Blue Lagoon, though locals often prefer the casual Sundhöllin public baths.',
      thing:'Natural wonders abound in the Golden Circle. Relax at the Blue Lagoon, take a day trip to Gulfoss waterfall, or spot the Northern Lights on a nighttime excursion. ',
      hotelurl:'https://www.tripadvisor.in/Hotels-g189970-Reykjavik_Capital_Region-Hotels.html',
      resturanturl:'https://www.tripadvisor.in/Restaurants-g189970-Reykjavik_Capital_Region.html',
      flighturl:'https://www.tripadvisor.in/Flights-g189970-Reykjavik_Capital_Region-Cheap_Discount_Airfares.html',
    },
    {
      id: 12,
      smallImg: 'img42.webp',
      largeImg:'/large42.jpg',
      location: 'Santorini, Greece',
      stars: 4.7,
      description: 'Experience beautiful sunsets and white-washed buildings.',
      rate: '$1350',
      detailDesc:'This Cyclades island in the Aegean Sea looks like a place straight out of a fairy tale, with candy-coloured houses carved into cliffs, sapphire waters, and chalk-white buildings topped with cobalt-blue domes. Roam the peaceful black-sand beaches or stroll the streets of one of Santorini’s charming villages (start at Imerovigli). And no matter where your day takes you, wind it down in beautiful Oia: It’s world-famous for its sunsets, which cycle through a kaleidoscope of colours in their spectacular nightly show.',
      thing:'There is more to this island than catching the sunset in Oia: Lounge by the black sand Kamari Beach, explore ancient Akrotiri, or hop on a boat tour to visit Nea Kameni. ',
      hotelurl:'https://www.tripadvisor.in/Hotels-g189433-Santorini_Cyclades_South_Aegean-Hotels.html',
      resturanturl:'https://www.tripadvisor.in/Restaurants-g189433-Santorini_Cyclades_South_Aegean.html',
      flighturl:'https://www.tripadvisor.in/Flights-g189433-Santorini_Cyclades_South_Aegean-Cheap_Discount_Airfares.html',
    }

  ];
  